name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            extension: librust_php_extension_sample.dylib
            php-version: '8.3'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, curl
          tools: composer:v2

      - name: Build PHP extension
        run: cargo build --workspace --all-features --release

      - name: Create artifact name
        id: artifact
        run: |
          PHP_VERSION="${{ matrix.php-version }}"
          OS_NAME="macos"∑
          ARTIFACT_NAME="rust-php-extension-sample-${PHP_VERSION}-${OS_NAME}.dylib"
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      - name: Rename extension
        run: cp target/release/${{ matrix.extension }} ${{ steps.artifact.outputs.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.artifact_name }}
          path: ${{ steps.artifact.outputs.artifact_name }}
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            rust-php-extension-sample-*/rust-php-extension-sample-*.dylib
